export const environment = {
    production: false,
    hmr: false,
    paynomix: false,
    surfside: false,
    wholesale: false,
    magic: false,
    mentom: true,
    apiURL: 'https://dashboard.mentom.com/api//api/',
    title: 'Mentom Payment',
    assetPathName: 'mentom',
    themeName: 'theme-mentom',
    themeColor: '#c41230',
    themeTransparentColor: '#c41230b3',
};
