export const environment = {
    production: false,
    hmr: false,
    mentom: false,
    surfside: false,
    wholesale: false,
    magic: false,
    paynomix : true,
    apiURL: 'https://api.paynomix.com:444/api/',
    title: 'Paynomix',
    assetPathName: 'paynomix',
    themeName: 'theme-default',
    themeColor: '#039be5',
    themeTransparentColor: '#039be599',
};